development:
  encoding: utf8
  username: root
  adapter: mysql2
  database: vidhelp_dev
  pool: 5
  timeout: 5000

test:
  encoding: utf8
  username: root
  adapter: mysql2
  database: alchemist_test
  pool: 5
  timeout: 5000

production:
  encoding: utf8
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASS'] %>
  host: <%= ENV['DB_HOST'] %>
  adapter: mysql2
  database: vidhelp_prod
  pool: 5
  timeout: 5000
